### PR TITLE
fix: prevent frontend search input from receiving focus

### LINKED ISSUE #417: It's still possible to write into search field with displayed SmartFAQs
When SmartFAQ input loses focus, it's possible to fill-in search form in the background.

Video: http://recordit.co/NNk1C0Qe0e

### PR DESCRIPTION
**Pull request by jaroslav-kubicek**
closes #417 (now finally 🙏 )<br/><br/><br/><url>LiveURL: https://smartfaq-fix-input-focus.surge.sh</url>

### CODE REVIEW

**Comment by kantord** [comment]
For me it's completely possible to interact with the background in Firefox and Chrome as well.

**Comment by kantord** [comment]
hmm somehow a commit that doesn't belong here appeared on this PR

**Comment by vborszeki** [comment]
@kantord I have also tested it locally and works totally fine even in Safari.

**Comment by kantord** [comment]
@vborszeki hmm so I'm doing something wrong maybe :thinking:

**Comment by jaroslav-kubicek** [comment]
> For me it's completely possible to interact with the background in Firefox and Chrome as well.

It's possible to write into it if FE input already has focus, but this should prevent it from receiving it

**Comment by jaroslav-kubicek** [comment]
so no focus in input => no interaction with it when you open SmartFAQ and hit any keyboard key

**Pull request merged**
