### PR TITLE
feat(faqs): show FAQ articles on root level as well

### LINKED ISSUE #670: Articles are not fetched for root categories
Since there's only one category in this booking state, we're forcing the user to make a completely unnecessary click

2018-08-17-153202_2746x1575_scrot

UPDATE: There is a bug in our root category query - we are not fetching articles for root categories (and it's not even possible)

- [ ]  step I. create new FAQ query merging `allFAQCAtegories` and `FAQCategory` into one query
- [ ] step II. update SmartFAQ to use this query and display articles on the root level

### PR DESCRIPTION
**Pull request by jaroslav-kubicek**
closes #670 

<br/><br/><url>LiveURL: https://smartfaq-show-articles-on-root.surge.sh</url>

### CODE REVIEW

**Comment by kantord** [comment]
> WIP - breadcrumbs for articles on root level broken, needs to be fixed in GraphQL + kiwicom/graphql#350 needs to be merged

**Comment by kantord** [comment]
> WIP - breadcrumbs for articles on root level broken, needs to be fixed in GraphQL + kiwicom/graphql#350 needs to be merged

I changed the name of the PR to reflect this

**Comment by jaroslav-kubicek** [comment]
ha, it was merged so it's not WIP anymore :) cc @kantord

**Comment by kantord** [comment]
Amazing! :tada:

**Comment by jaroslav-kubicek** [comment]
ping @kantord @vborszeki @jalbertsr

**Pull request merged**
