### PR TITLE
Added cypress fixture for submiting article question

### LINKED ISSUE #284: Find a way not to actually submit feedback form during integration tests
Currently the action of submitting the form is commented out to avoid `POST`ing many new feedback to the backend. https://github.com/kiwicom/smart-faq/blob/master/cypress/integration/LoggedOutStaticFAQ.cy.js#L75

Ideally we should test that functionality without creating a new feedback at every request.

Ideas:
- Agree with backend on some text that can be easily filtered + removed. This will allow us to test the real feedback submission.
 - Mock the response somewhow

Obstacles:
- We are running integration tests against a real deployment at surge.sh

### PR DESCRIPTION
**Pull request by dinodsaurus**
closes #284 
It is pretty easy when you have a single post request...
I will try the same thing on login, we will see how that goes<br/><br/><br/><url>LiveURL: https://smartfaq-cypress-comment-fixture.surge.sh</url>

### CODE REVIEW

**Comment by dinodsaurus** [comment]
Yep, makes sense, will add it 👍 
Regarding mocking login functionality, what do you think about it, should we go in that direction or not? Please check #280

**Comment by git-toni** [comment]
I believe your approach works best in the case of login, but I'm dubious we need to mock login? 

Shouldn't we integrate-test everything as close to the user as possible? Just not having side-effects such as flooding the backend with new feedback messages. Imho we can afford to *actually* login, otherwise we will need to mock bookings, etc as well.

What do you think?

**Comment by dinodsaurus** [comment]
I think the same, but the only thing that concerns me is this `cy.wait(1000);` timeout.
But yea.. maybe im over engineering it at this point of time, lets see how it goes and then adapt 😁

**Comment by git-toni** [comment]
One option to "clean-up" code of `cy.wait`s would probalby be overwrite some timeouts in the `cypress.json` ? https://docs.cypress.io/guides/references/configuration.html#Timeouts

**Comment by edgarordonez** [comment]
Hi! @git-toni, @dinodsaurus 

I'm not sure about what it's the better approach, but probably, not has sense mock all the responses in the e2e test, anyway, I made a new command for mock all the requests, either HTTP as login or a GraphQL. You can see it in the last PR [#280](https://github.com/kiwicom/smart-faq/pull/280).

I did a mock of all the requests in that test, I guess isn't necessary, I could change it. We can discuss in that other PR. 

Thanks!

**Pull request merged**
