### PR TITLE
build: remove Babel runtime

### PR DESCRIPTION
**Pull request by oreqizer**

### CODE REVIEW

**Comment by jaroslav-kubicek** [comment]
it's impossible to import `babel-runtime`, so I adjusted the PR a little bit + made orbit dependencies as peer. check it pls if it's ok @oreqizer

**Comment by kantord** [comment]
If `babel-runtime` isn't actually being removed, please also change the commit message

**Comment by kantord** [comment]
@jaroslav-kubicek what happened here? :thinking: https://github.com/kiwicom/smart-faq/commit/35d062f9a7b07eac3225e642799721f1787576ab how was this commit created?

**Comment by jaroslav-kubicek** [comment]
huh, I haven't noticed, Github took the original one 🤕

**Comment by kantord** [comment]
WeirdHub™

**Pull request merged**
