### PR TITLE
Tablet landscape design

### LINKED ISSUE #342: Refactor idea: create react components for responsive breakpoints
Currently we use two ways to implement responsive design. One is by using `desktopOnly` or `mobileOnly` CSS classes. Another is using `react-responsive` like this:

```jsx
<MediaQuery query="screen and (min-width: 320px) and (max-width: 480px)">
  ... stuff ...
</MediaQuery>
```

I think it'd be useful to create components that encapsulate the media queries for each breakpoint, so that they don't have to be defined manually everywhere. Something like
```jsx
<MobileImplementation>
  ... stuff ...
</MobileImplementation>
```

We should also get rid of the CSS helper classes for the sake of simplicity.

### LINKED ISSUE #502: Update layout for tablets
Tablet in landscape mode should display normal desktop version, just with tighter FAQ column: https://zpl.io/a74G9qp

Tablet in portrait will be similar to mobile in landscape - intro & login screens centered  https://zpl.io/begmngq but images and texts like "We're here for you. First, let's narrow down your request." will be shown

### PR DESCRIPTION
**Pull request by kantord**
fixes #342 
fixes #502<br/><br/><br/><url>LiveURL: https://smartfaq-update-layout-for-tablets.surge.sh</url>

### CODE REVIEW

**Comment by jalbertsr** [comment]
for iPad I see faq with the mobile design 

not sure it should look like this :/
screenshot

**Comment by kantord** [comment]
You're right. How about now?

**Comment by jalbertsr** [comment]
fixed 👍 
I also noticed this in the logout/intro screens
screenshot

I think you can fix it in this issue, but it's up to you if you prefer to do it in another issue apart.

**Comment by kantord** [comment]
It was pretty easy to fix it, so I just did it here.

Note: I think this MR doesn't need to be squashed :-) It might be better to not squash it even, since there's a lot of refactoring here and I think it useful to keep those in separate commits.

**Comment by jalbertsr** [comment]
also for these screens pls 

gif

**Pull request merged**
