### PR TITLE
New header responsive mobile

### LINKED ISSUE #416: New header in responsive mobile portrait/landscape
New headers should be implemented in mobile versions to better the usability for our users.
Landscape related issues: #401 #405 
smallheaderlogin copy 3

The header should disappear when scrolling down: https://zpl.io/VOkXen1

Designs (portrait): https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/dashboard?seid=5b1fd0955639ebad77152b5f

Designs (lanscape): https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/dashboard?seid=5b1fd052e02db4652256c1da

### PR DESCRIPTION
**Pull request by edgarordonez**
Close #416

- The new mobile header according to the new designs

image
<br/><br/><br/><url>LiveURL: https://smartfaq-416-new-header-responsive-mobile.surge.sh</url>

### CODE REVIEW

**Comment by kantord** [comment]
I rebased + added fix for search bar issue + I found that the back button is hard to click so I fixed that as well. Seems fine to me now :-)

**Comment by kantord** [comment]
I believe we have to either clean up the commits and their messages (`git rebase -i`) or we have to squash this. I don't know which one is better.

**Comment by kantord** [comment]
Conflicts resolved @jalbertsr

**Comment by jalbertsr** [comment]
There is the problem that faqs are not loading the correct faqs categories for the booking status, until you press(and load) the booking. 

This error apeared in sentry while testing: https://sentry.skypicker.com/kiwicom/smartfaqstaging/issues/1289237/
 
There should be only one close button (`X`), also the "Help" header should be smaller 
screenshot

In landscape there should be no "Help" header
screenshot

**Comment by kantord** [comment]
Thanks for the review! Working on the fix

**Comment by jalbertsr** [comment]
@kantord can you maybe use the strategy you commented with me of using strings instead of booleans? the same we did for `ExtraInfoState` context, I think with this solution we'll get rid of these sentry errors https://sentry.skypicker.com/kiwicom/smartfaqstaging/issues/1362002/?query=is:unresolved

**Comment by kantord** [comment]
@jalbertsr I can, but it'd be great to find a way to consistently reproduce them before I do the fix. Otherwise, how will I know it worked :-)

**Pull request merged**
