### PR TITLE
build(orbit-components): enable tree-shaking for orbit-components

### LINKED ISSUE #572: Use "babel-plugin-orbit-components" plugin to optimize bundle
Use this plugin to avoid loading the whole lib: https://github.com/kiwicom/babel-plugin-orbit-components

### PR DESCRIPTION
**Pull request by kantord**
fixes #572

### CODE REVIEW

**Comment by jaroslav-kubicek** [comment]
uni tests are failing, cc @kantord

**Comment by kantord** [comment]
For some reason, I don't get the same failures in local

**Comment by jaroslav-kubicek** [comment]
eslint error

**Comment by kantord** [comment]
It was more than that, but it should work now, let's see.

**Pull request merged**
