### PR TITLE
unify width of right column

### LINKED ISSUE #437: UI improvement: unify widths of right column for signed-in and anonymous user
Please, let's use 650 pix (the current size for signed-in user) for both signed-in and anonymous user:

snimek obrazovky 2018-06-15 v 11 21 48
snimek obrazovky 2018-06-15 v 11 23 25

Sorry about the inconsistency in design... 😇

### PR DESCRIPTION
**Pull request by vborszeki**
references #437<br/><br/><br/><url>LiveURL: https://smartfaq-437-unified-width-of-right-column.surge.sh</url>

### CODE REVIEW

**Comment by jaroslav-kubicek** [comment]
I'm curious, @jalbertsr you can't merge?

**Comment by jaroslav-kubicek** [comment]
I merged the MR, but IMHO not it's not finished fully (I left the issue open) - the same width should be applied to login & intro screens

**Comment by jalbertsr** [comment]
I had not merged it yet because we were talking about whether it was better to do a rebase instead of `Merge branch 'master' into 437-unified-width-of-right-column`, but we said it was ok, just rebase from now on.

It also feels strange to me this width change, when going form intro page to faq page.

**Comment by vborszeki** [comment]
I was also thinking about the discrepancy of those sizes initially, but to me the wider login & intro screen seemed that it has too much unnecessary whitespace.

**Comment by jaroslav-kubicek** [comment]
if you are in doubts regarding the UI, please always ask @mjancik

**Comment by jaroslav-kubicek** [comment]
> I had not merged it yet because we were talking about whether it was better to do a rebase instead of Merge branch 'master' into 437-unified-width-of-right-column

huh, ok, I overlook this.

**Comment by vborszeki** [comment]
> the same width should be applied to login & intro screens
> 
I have discussed this question with @mjancik and he said that the current design is ok, so I think we can close the issue.

**Comment by jaroslav-kubicek** [comment]
superb, thanks, then just close it

**Pull request merged**
