### PR TITLE
Automatically redirect logged in user

### LINKED ISSUE #137: Redirects to booking page automatically
**Acceptance criteria**

- When the smart FAQ is opened and the user is logged in on the frontend, automatically redirect to booking page (so intro page with two buttons is not shown)
- For non-logged in user, it works as before

### PR DESCRIPTION
**Pull request by kantord**
<br/><br/><br/><url>LiveURL: https://kiwicomsmart-faq-jssetcawnv.now.sh
</url>
</url>

fixes #137

### CODE REVIEW

**Comment by git-toni** [comment]
Please add the issue that this is fixing, I believe it's #137 in this case?

Also, IMHO, while this will work well I believe it's worth to think about making a HOC out of this logc, something like `requireLoggedOut`. Then export a `requireLoggedOut`-decorated `IntroPage` component, will will redirect upon mounting if the user is logged-in.

This will allow us to apply the same logic to other components/screens that only should be rendered when there is no session present.

**Comment by git-toni** [comment]
@kantord Agree `requireLoggedOut` is awkward :sweat_smile: The name was just a suggestion, also `loggedOutPage` or sth alike would convey the point. 

Not sure I understand your login page suggestion, what would it do exactly? Check that it's logged-in or logged-out? Redirect where? Or parameterized redirection?

**Comment by kantord** [comment]
Well, normally you'd see something like `requireLoggedIn` which would redirect to a login page if the user is not logged in, then the login page would redirect back to the original page after login.

In our case we have something similar, but it's more a switch, because we don't *require* the user to log in.

Eh. That also sounds awkward and confusing... Actually I'm content with the current solution :-D

**Comment by git-toni** [comment]
Yes but the requirement for this page is for the user to be *logged out*, not logged-in.

I think this same logic(ie. requiring logged-out to be rendered) applies to other screens as well, so making an HOC out of it feels better.

**Comment by kantord** [comment]
hmm, login is required for the upcoming booking part only, though, isn't it?

**Comment by git-toni** [comment]
Please ignore what I just said, ofc we are talking about `requireLoggedIn` not  `loggedOut`. 

I was thinking about a completely different topic :smile_cat:

**Comment by kantord** [comment]
Ok now?

**Pull request merged**
