### PR TITLE
Fix mobile scroll

### LINKED ISSUE #402: "contact us" unreachable on iPad with longer article
on IPad, i have problems scrolling to the bottom of longer articles where contact us link is. the page keeps cropping it out of the frame

Video: https://monosnap.com/file/XTOJjJlxQnehOcfgGYxAPRZ1o3m2mK
same issue for iPhone: https://monosnap.com/file/EDrvCLtR5gYCHOph6Qy74fMNMfUjE0

### PR DESCRIPTION
**Pull request by kantord**
fixes #402 
also fixes https://github.com/kiwicom/smart-faq/issues/374
<br/><br/><br/><url>LiveURL: https://smartfaq-fix-issue-402.surge.sh</url>

### CODE REVIEW

**Comment by kantord** [comment]
oooppps, wrong base

**Comment by kantord** [comment]
fixed base issue, should be fine now

**Comment by jalbertsr** [comment]
I see this: 
screenshot

**Comment by kantord** [comment]
@jalbertsr thanks, will look into it :-)

**Comment by kantord** [comment]
@jalbertsr it seems that that issue has not been introduced by this PR and is not related to the issue that it's solving.

**Comment by jaroslav-kubicek** [comment]
#398 is not fixed, link is not visible

Also I have two scrolls in the list of categories - one for categories, second for the whole content

see pictures below:

img_5042
img_5041

**Comment by kantord** [comment]
Oh indeed, i just tried on an actual iPhone and I can reproduce it. Thanks !

**Comment by kantord** [comment]
bb7d3a59-bc10-4576-85da-3e1da6b3c04e

Also this happens. 🤔

**Comment by kantord** [comment]
#398 is not fixed, but that can be fixed in another pull request I think.

Everything else seems to work for me now, but I'll test again on an actual phone

**Comment by kantord** [comment]
Everything seems to work now :-) There's a small glitch still, cause by this: https://github.com/kiwicom/smart-faq/issues/435, but https://github.com/kiwicom/smart-faq/issues/402 is fixed regardless, so I think this PR can be merged.

**Pull request merged**
